name: shop_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^0.2.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  conditional: ^0.0.1
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
     - family: Black and Violet
       fonts:
         - asset: assets/fonts/Black and Violet.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
